# Generated by Django 4.1.6 on 2023-02-13 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True, verbose_name='First name')),
                ('lname', models.CharField(max_length=200, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('products', models.ManyToManyField(blank=True, to='parties.partyticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
