# Generated by Django 4.1.6 on 2023-02-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customer_products_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forget_pass_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
