# Generated by Django 4.1.6 on 2023-02-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_store'),
        ('admin_panel', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='Csutomer name'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='admin_panel.cartitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
