# Generated by Django 4.1.6 on 2023-02-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_remove_partyticket_venue'),
        ('admin_panel', '0003_alter_cart_customer_alter_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.partyticket'),
        ),
    ]
